# Generated by Django 4.2.26 on 2025-11-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterPol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default=642513, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
