# Generated by Django 4.2.26 on 2025-11-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterPol', '0003_alter_address_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
