# Generated by Django 4.2.26 on 2025-11-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterPol', '0004_alter_address_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='partner_min_price',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='product_type_ratio',
        ),
        migrations.AddField(
            model_name='partner',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
