# Generated by Django 4.2.26 on 2025-11-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterPol', '0005_remove_product_partner_min_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='partner_min_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_type',
            name='product_type_ratio',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
            preserve_default=False,
        ),
    ]
