# Generated by Django 4.2.26 on 2025-11-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterPol', '0006_product_partner_min_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='partner_min_price',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='product_type_ratio',
        ),
    ]
