# Generated by Django 4.2.26 on 2025-11-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterPol', '0007_remove_product_partner_min_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='partner_min_price',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_type',
            name='product_type_ratio',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
