# Generated by Django 4.2.26 on 2025-11-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterPol', '0008_product_partner_min_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='discount',
        ),
    ]
