# Generated by Django 4.2.26 on 2025-11-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterPol', '0009_remove_partner_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('material_scrap_percentage', models.FloatField()),
            ],
        ),
    ]
